### ISSUE TITLE
Settings menu overhaul

### ISSUE THREAD

**Issue by yshterev** [videojs/videojs-settings-menu#3]
Hi @gkatsev @nickygerritsen  - I did some overhauling of the plugin, inspired by the settings menu of youtube. 

[![settings.gif](https://s3.amazonaws.com/uploads.hipchat.com/605877/4217317/kcCNX0DukwPpCg0/settings.gif)

Showing submenus on the side can be problematic for smaller players if titles are long and it is not very eye-pleasing. 

Loading submenus in the same panel removes the limitations for displaying content. The plugin eventually can support multi-level nesting, the caption settings can go there too, and user experience will not suffer even on very small players (if settings menu is bigger than the player container it should become scrollable)

I did many modifications on the original code. It is still WIP and some things probably can be done better. I was wondering if you would accept PR on something like this or I should keep it as a separate project. You can check the code and test it in [my fork](https://github.com/yshterev/videojs-settings-menu)

**Comment by bigt11** [comment]
@yshterev I want to test this out.  I went to your fork, but was not able to figure out how to compile it so I can run it.  I see the files in your src folder, but it seems like that need to be compiled some how??  Can you please provide instructions, I am  fairly new to the videojs plugins scene.

**Comment by yshterev** [comment]
1. Clone my fork
2. Run `npm install` in the root folder, I think it will run the build task too. If you don't see a dist folder after install, run `npm run build`.
3. Run `npm start` - It should start a localhost web server with working example
